### ISSUE TITLE
Mother/Father Origin Does Not Affect Skin

### ISSUE THREAD

**Issue by Duderocktv** [boermansjo/ESX_HUD#12]
I'm assuming this is already known, but it wasn't listed in the issues, so I'll go ahead and add it here.

Choosing Male/Female for Mother/Father Origin, changes nothing. 
Male changes Male, Female Changes Male.
Slider for "Ressemblance" towards Mother or Father also not working.

**Comment by boermansjo** [comment]
This feature Will not work because I use skinchanger. Maybe it can be a great idea to update skinchanger too with more options.
Soon when you select male, you only see the male faces. For female you will have a few more options and complete outfits.

**Comment by ZockerBoysHD** [comment]
@boermansjo  what does "soon" mean tho. its been several months since your post

**Comment by boermansjo** [comment]
Not sure if people are still looking for a menu like this...
This one doesn't work with all the new updates.

**Comment by ZockerBoysHD** [comment]
Yes people are. I know at least a dozen of server who are using your script. mine included. Players really really like it. 
Only Problem is that it doesnt have the Clothing shop feature with restricted areas of the skincreator visible. 
The Gender Problem with male / female skins was the only thing i was able to fix myself.  Also if ur playing on a higher resolution (4K for example) the "Content" of the skincreator doesnt get Upscaled properly but the Background Frame / The Colored Background does it. So u have to Scroll where the Content/ the selectors are otherwise you wont see the Other Stuff to choose from

**Comment by boermansjo** [comment]
Glad to hear that. To be honest, I had some struggling to keep this updated.
But I have done a lot. Scaling is no more an issue.
I am also working an a usable clothshop that works wel with this. When it is all ready I update the GitHub.

**Comment by ZockerBoysHD** [comment]
thats nice to hear. Will the Female Clothing be fixxed  with the next update? or more general the femal skin system?

**Comment by boermansjo** [comment]
Origin has been removed.
