### ISSUE TITLE
Old skin menu opens together with skinchanger

### ISSUE THREAD

**Issue by lvp11** [boermansjo/ESX_HUD#2]
Hey!

How do i stop the old skin menu to open with skinchanger, when player first login?

Thanks!

(Sorry for my bad english).

**Comment by XvenDeR** [comment]
It's probably your esx_skin popping in.

You can stop it by going to esx_skin/client/main.lua
`		if firstSpawn then
			ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin, jobSkin)
				if skin == nil then
					TriggerEvent('skinchanger:loadSkin', {sex = 0}, OpenSaveableMenu)
				else
					TriggerEvent('skinchanger:loadSkin', skin)
				end`

Now you have to think something with this, since this skincreator isn't compatible with esx_skin and esx_clotheshop yet.

You can change or even disable this
`TriggerEvent('skinchanger:loadSkin', {sex = 0}, OpenSaveableMenu)`
So it will make that "old skin menu" as you said, to stop popping out when first time creating character.

**Comment by SwAtRaNgEr** [comment]
so just delete and replace with  TriggerEvent('skinchanger:loadSkin', {sex = 0}, OpenSaveableMenu)?

**Comment by boermansjo** [comment]
I will close this issue because it is indead the esx_skin that causes this problem.
When I have time, I will port all the critical parts from esx_skin into this skinchanger so that we only need 1 script.
